Add CI test for ring appearing in the compiled binary

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -35,6 +35,10 @@ jobs:
         run: |
           cd bindings/tbdex_uniffi/libtargets/aarch64_apple_darwin
           ./build
+          if cargo tree | grep -q ring; then
+            echo "::error title=ring library found in compiled binary::The ring library has unclear licensing and we are not sure if it can be put in the compiled binary"
+            exit 1
+          fi
       - name: Upload .dylib
         uses: actions/upload-artifact@v4.0.0
         with:
@@ -52,6 +56,10 @@ jobs:
         run: |
           cd bindings/tbdex_uniffi/libtargets/x86_64_apple_darwin
           ./build
+          if cargo tree | grep -q ring; then
+            echo "::error title=ring library found in compiled binary::The ring library has unclear licensing and we are not sure if it can be put in the compiled binary"
+            exit 1
+          fi
       - name: Upload .dylib
         uses: actions/upload-artifact@v4.0.0
         with:
@@ -67,6 +75,10 @@ jobs:
         run: |
           cd bindings/tbdex_uniffi/libtargets/x86_64_unknown_linux_gnu
           ./build
+          if cargo tree | grep -q ring; then
+            echo "::error title=ring library found in compiled binary::The ring library has unclear licensing and we are not sure if it can be put in the compiled binary"
+            exit 1
+          fi
       - name: Upload .so
         uses: actions/upload-artifact@v4.0.0
         with:
@@ -82,6 +94,10 @@ jobs:
         run: |
           cd bindings/tbdex_uniffi/libtargets/x86_64_unknown_linux_musl
           ./build
+          if cargo tree | grep -q ring; then
+            echo "::error title=ring library found in compiled binary::The ring library has unclear licensing and we are not sure if it can be put in the compiled binary"
+            exit 1
+          fi
       - name: Upload .so
         uses: actions/upload-artifact@v4.0.0
         with:
