Issue #97: Check out the git tag

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -10,16 +10,16 @@ on:
 jobs:
 
   # Disable for now
-  #run-ci:
-  #  # This will run CI and also publish the Kotlin release to the TBD Artifactory repo manager
-  #  name: Run CI
-  #  #TODO Update this to TBD org when done testing
-  #  uses: ALRubinger/tbdex-rs/.github/workflows/ci.yml@main
-  #  secrets: inherit   
+  run-ci:
+    # This will run CI and also publish the Kotlin release to the TBD Artifactory repo manager
+    name: Run CI
+    #TODO Update this to TBD org when done testing
+    uses: ALRubinger/tbdex-rs/.github/workflows/ci.yml@main
+    secrets: inherit   
 
   git-tag:
     runs-on: ubuntu-latest
-    #needs: run-ci
+    needs: run-ci
     outputs:
       RELEASE_TAG: ${{ steps.set-version-and-tag.outputs.RELEASE_TAG }}
       RELEASE_VERSION: ${{ steps.set-version-and-tag.outputs.RELEASE_VERSION }}
@@ -100,16 +100,76 @@ jobs:
           git add -Av
           git commit -m "[TBD Release Manager 🚀] Setting next development version after $version to: $nextVersion"
           git push origin main
-
-  test-things:
-    name: Test things
+ 
+  kotlin-release-to-tbd-artifactory-and-maven-central:
+    name: Release Kotlin to TBD Artifactory and Maven Central
     needs: git-tag
     runs-on: ubuntu-latest
     steps:
+    
+      # Check out the tag we created above
       - uses: actions/checkout@v4
         with:
           submodules: true
           ref: ${{ needs.git-tag.outputs.RELEASE_TAG }} # Check out the tag we created above
-        
+    
+      # Set up JDK
+      - name: Set up JDK 11
+        uses: actions/setup-java@v3
+        with:
+          distribution: "adopt"
+          java-version: "11"
 
-        
+      # Cache Maven repo
+      - uses: actions/cache@v3
+        with:
+          path: ~/.m2/repository
+          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+          restore-keys: |
+            ${{ runner.os }}-maven-
+
+      # Package up the native binaries
+      #TODO Centralize this block as we re-use it via copy/paste right now
+      - name: Download MacOS aarch64 Native Library
+        uses: actions/download-artifact@v4.0.0
+        with:
+            name: aarch64-apple-darwin-dylib
+            path: bound/kt/src/main/resources/
+      - name: Download MacOS x86_64 Native Library
+        uses: actions/download-artifact@v4.0.0
+        with:
+          name: x86_64-apple-darwin-dylib
+          path: bound/kt/src/main/resources/
+      - name: Download Linux x86_64 GNU Native Library
+        uses: actions/download-artifact@v4.0.0
+        with:
+          name: x86_64-unknown-linux-gnu-so
+          path: bound/kt/src/main/resources/
+      - name: Download Linux x86_64 MUSL Native Library
+        uses: actions/download-artifact@v4.0.0
+        with:
+          name: x86_64-unknown-linux-musl-so
+          path: bound/kt/src/main/resources/
+
+      - name: Deploy Release Version of Kotlin Project to Maven Central
+        run: |
+            # cd into the Kotlin project
+            cd bound/kt/
+
+            # Publish to Sonatype
+            # Precondition check: Only attempt to publish artifact if we have credentials
+            if [ -n "${{ secrets.SONATYPE_PASSWORD }}" ]; then
+                # Maven deploy lifecycle will build, run tests, verify, sign, and deploy
+                mvn deploy \ 
+                  --batch-mode \
+                  --settings .maven_settings.xml \
+                  -P ossrh,sign-artifacts
+            else
+                echo "Error: No credentials"
+                exit 1
+            fi
+        env:
+          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
+          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
+          SIGN_KEY_PASS: ${{ secrets.GPG_SECRET_PASSPHRASE }}
+          SIGN_KEY: ${{ secrets.GPG_SECRET_KEY }}
